export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const MOVIE_SAVE_REQUEST = 'MOVIE_SAVE_REQUEST'
export const MOVIE_SAVE_SUCCESS = 'MOVIE_SAVE_SUCCESS'
export const MOVIE_SAVE_FAIL = 'MOVIE_SAVE_FAIL'

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST'
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS'
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL'
export const MOVIE_DELETE_RESET = 'MOVIE_DELETE_RESET'